# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Run all tests for FkGallery project"
  lane :all_tests do
    cocoapods
    run_tests(device: "iPhone 7")
  end

  desc "Run only unit tests for FkGallery project"
  lane :tests do
    cocoapods
    run_tests(device: "iPhone 7", skip_testing: "FkGalleryUITests")
  end

  desc "Build FkGallery project"
  lane :build do
    cocoapods

    cert
    sigh(app_identifier: '*', adhoc: '1')

    increment_build_number

    run_tests(device: "iPhone 7", skip_testing: "FkGalleryUITests")

    commit_version_bump

  end

end
